baseURL: "https://www.eliasdorigoni.com/"
languageCode: "es"
title: "Elías Dorigoni"
Paginate: "10"
PaginatePath: "pagina"
disqusShortname: "eliasdorigoni"
hrefTargetBlank: true

blackfriday:
  extensionsmask: ["autolink"]

params:
    author: "Elias Dorigoni"

taxonomies:
    categoria: categorias
    serie: series
DefaultContentLanguage: es
